### ISSUE TITLE
CODEOWNERS

### ISSUE THREAD

**Issue by salecharohit** [6mile/DevSecOps-Playbook#5]
In the Source code management add about the CODEOWNERS file as a very strong recomendation

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

**Comment by 6mile** [comment]
Heya mate, this is a great idea.  I'll add it this weekend!  I wasn't even aware of the CODEOWNERS file so I'm learning something.  Thanks!
